# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6cQ91ZLpjBmz2ZkCmnNkJI2x3CNPkwW

# PRIMEIRA AULA
"""

print('olá mundo')

"""# SEGUNDA AULA
## OPERADORES ARITMÉTICOS
"""

# adisão
10+2

# subtração
10-2

# multiplicação
10*2

# divisão
10/2

# divisão inteira
10//2

# resto da divisão
10%2

# potenciação
10**2

"""## OPERADORES RELACIONAIS"""

# MENOR
10<2

# menor ou igul
10<=2

# MAIOR
10>2

# MAIOR OU IGAUL
10>=2

# IGAUL
7==7

# DIFERENTE
7!=7

"""## OPERADORES LÓGICOS
 ### *AND
 ### *OR
### *NOT

## TABELA DA VERDADE

and
"""

print(10 > 2 and 4 < 6) # v and v-v
print(10 > 2 and 4 > 6) # v and f-f
print(10 < 2 and 4 < 6) # f and v-f
print(10 < 2 and 4 > 6) # f and f-f

"""or"""

print(10 > 2 or 4 < 6) # v or v-v
print(10 > 2 or 4 > 6) # v or f-v
print(10 < 2 or 4 < 6) # f or v-v
print(10 < 2 or 4 > 6) # f or f-f

"""not"""

print(not 10 > 2) # v-f
print(not 10 < 2) # f-v

"""##VARIÁVEIS"""

# nome da variável é "x" que armazena o valor 10 em um espaço na memória
x = 10
print(x) # utilizar a eferencia no nome atribuido



"""## VISUALIZAÇÃO DE VARIÁVEIS DE TEXTOS

"""

print("conhecendo o conmando pint")
x = 8
print(x)

y=10
soma=x+y
print(soma)

nome ="ramonilson"
print(nome)

x=5
print("o valor de x é",x)

print('o valor de x é', x,'e o dobro é',x*2)

print('Eu,', nome,'tirei', x,'na prova de python')

y = 10; z = 20 + x - y
print('Declarar várias variáveis na mesma linha:', y, z)

X=10
type(x)
print('x',type(x))

nome ='ramonilson'
print('nome', type(nome))

num='100'
num_convert = int(num) #converter variável
print('num',type(num))
print('num_convert',type(num_convert))

num_float = float(num)
print('num_float', num_float)

nome = input('digite o nome do usuario') # aguanda o usuario digitar algo

valor = input('digite a nota ')
print(nome,'sua nota foi', valor)

valor = input('digite o valor produto:')
print(valor)

desconto= valor -5

valor_convet = int(valor)
desconto = valor_convet -5
print(desconto)



"""## CONDICIONAL"""

# if
if 5 < 10:
  print('verdade')

#if / else
num1 =10
num2 =5
if num1 > num2:
  print('num1 é o maior número')
else:
  print('num2 é o maior número')

# if / elif / else
num1 =10
num2 =10
if num1 > num2:
  print('num1 é o maior número')
elif num1 < num2:
  print('num2 é o maior número')
else:
  print('os números são iguais')

"""## CONDICIONAL COM OPERADORES LÓGICOS"""

num1 = 10
num2 = 5
num3 = 2
if (num1 > num2) and (num1 > num3):
  print('num1 é o maior número')
else:
  print('o num1 não é maior número')

"""##  LISTAS, TUPLAS E DICIONÁRIOS"""

# listas
[1,2,3,5,6,7,8,9]

#tupla
(1,2,3,5,6,7,8,9)

# dicionário
{'num1':1,'num2':2}

"""## LISTA"""

lista =[5,'ramonilson',8.9]

type(lista)

lista.append('raisa') # adicionar um elemento na lista

print(lista)
print(lista[1])

"""## TUPLA"""

tupla = (5,'ramonilson',8.9)

type(tupla)

tupla.append('raisa')

print(tupla)

"""## DICIONÁRIO

"""

dicionário = {'nome':'ramonilson','cidade':'areia branca'}

type(dicionário)

print(dicionário)

print(dicionário['nome'])

dicionário['ultimo_nome'] = 'silva'

print(dicionário)

"""## FOR


"""

# for renge
for contador in range(10):
  print(contador)

# for range + brenk
for contador in range(1000):
  print(contador)
  if contador == 2:
    break

lista = ["teste1","teste2"]



# for simples
for val in lista:
  print(val)

# for com enumerate
for i, val in enumerate(lista):
  print(i,val)

"""## FOR COM OPERADORES COMPOSTOS"""

lista2 = [2,3,4]

for val in lista2:
  val += 1
  print(val)

for val in lista2:
  val *= 2
  print(val)

"""## WHILE"""

val = 1
while (val < 6):
  val *= 2
  print(val)

# while com else
val = 10
while val < 6:
  val += 2
else:
  print('valor de val é:',val)